version: '3.7'

services:
  db:
    image: mysql:8
    container_name: marking_mysql
    restart: always
    environment:
      MYSQL_DATABASE: marking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marking_backend
    command: gunicorn --chdir msp marking_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./msp/staticfiles:/app/msp/staticfiles
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/marking
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: marking_frontend
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend/dist:/frontend_dist

  nginx:
    image: nginx:alpine
    container_name: marking_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./msp/staticfiles:/static
      - ./frontend/dist:/frontend_dist
    depends_on:
      - web
      - frontend

volumes:
  db_data:
