version: '3.8'

services:
  db:
    image: mysql:8
    container_name: marking_mysql
    restart: always
    environment:
      MYSQL_DATABASE: marking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: marking_backend
    command: gunicorn marking_system.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/marking
    volumes:
      - .:/app

volumes:
  db_data:
